server:
  servlet:
    context-path: ${context_path}
  port: ${port}

spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  application:
    name: user-service
    
opentracing:
  jaeger:
    udp-sender:
      host: ${jaeger_udp_sender_host}
      port: ${jaeger_udp_sender_port}