server:
  servlet:
    context-path: /user-service
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_info
    username: root
    password: root
  application:
    name: user-service
    
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831